# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1og9nxqoxKChaHHBUgNVYIgx6fqtMjCMd
"""

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

df = sns.load_dataset('tips')

df.head()

df.shape

df.describe()

df.columns

df.dtypes

df['day'].dtype

df['day'].unique()

df['size'].unique()

df['time'].unique()

df.groupby('sex')['smoker'].value_counts()

df.groupby('day', observed=False)['time'].value_counts()

df['day'].count()

df['tip'].count()

len(df)

df = sns.load_dataset('tips')

sns.countplot(data=df, x = 'sex', hue='smoker')
plt.title('Homens e mulheres fumantes e não fumantes')
plt.show()

dados = df.groupby(['sex', 'smoker']).size().unstack()
print(dados)

dados.plot(kind='bar')
plt.show()

dados.plot(kind='line')
plt.show()

dados.plot(kind='hist')
plt.show()

dados['Yes'].plot(kind='pie')
plt.show()

dados['Yes'].plot(
    kind='pie',
    autopct='%1.1f%%'
)
dados['Yes'].plot(
    kind='pie',
    autopct='%1.1f%%'
)

dados.plot(kind='bar')
plt.show()

dados.plot(kind='bar', figsize=(8,5))
plt.show()

dados.plot(kind='bar', rot=0)

"""Qual sexo dá maiores gorjetas?"""

df.groupby('sex')['tip'].mean().round(2)

df.groupby('sex')['tip'].mean().round(2).plot(kind='bar')
plt.show()

"""Qual dia tem maior faturamento?"""

df.groupby('day')['total_bill'].sum()

df.groupby('day')['total_bill'].sum().round(2).plot(kind='bar')
plt.show()

"""Quantidade de fumantes e não fumantes"""

df['smoker'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.ylabel('')
plt.show()

"""Qual horário possui mais clientes?"""

df['time'].value_counts().plot(kind='bar')
plt.show()

"""Média de contas por horário"""

df.groupby('time')['total_bill'].mean().plot(kind='bar')
plt.show()

"""Distribuição das contas"""

df['total_bill'].plot(kind='hist')
plt.show()

"""Relação entre conta e gorjeta"""

plt.scatter(df['total_bill'], df['tip'])
plt.xlabel('conta')
plt.ylabel('gorjeta')
plt.show()

"""Comparar fumantes e não fumantes"""

df.groupby('smoker')['total_bill'].mean().plot(kind='bar')
plt.show()



"""Praticar filtros"""

df[df['tip'] > 5]

df[df['size'] >= 3]

"""Combinar filtros"""

df[(df['sex'] == 'Male') & (df['smoker'] == 'Yes')]

"""Outros testes"""

df.groupby('day')['total_bill'].min().plot(kind='bar')

